### ISSUE TITLE
Data not rendered on Companion app

### ISSUE THREAD

**Issue by bpetrikovics** [SNoof85/lovelace-tempometer-gauge-card#29] opened 2021-02-18 08:58 UTC
**Describe the bug**
I saw there was another mobile related issue but this one seems completely different so opened a separate issue for it. On my Pixel 3a and the official Companion app (current app store version) the data on the graph is not rendered at all (see screenshot).

**Version of the card**
Version : 1.2 (actually 1.2.1 but version string likely not updated in the code)

**Screenshots**
![Screenshot_20210217-094712](https://user-images.githubusercontent.com/9517578/108331341-f6a2d400-71ce-11eb-90cf-6c79c34fa0cc.png)

**Desktop (please complete the following information):**

N/A - Companion app 2021.1.1-full

**Additional context**
Interesting enough same app version on a Nexus 9 table displays the data correctly.  This could be related to the internal webview that the Companion app is using (Pixel 3a is on most recent version of everything while the Nexus 9 is using an older OS release).
It does not seem to be theme related, I tried both the default UI theme and a couple others, doesn't seem to make any difference. Not sure how I could pull any kind of debug information out of the Companion app to help here.

**Comment by SNoof85** [comment] 2021-02-18 20:09
I use it everyday on comanion app on my oneplus 6t and no issue.
Strange. Did you tried to kill the app and re-open it ?

**Comment by bpetrikovics** [comment] 2021-02-18 22:00
Yes, tried that, tried to reboot the device, pretty much everything I could think of.

**Comment by bakboord4** [comment] 2021-02-20 17:20
The same problem here using:
Browser: Safari (MacOS and IOS)
and Companion.

After reboot in MacOS following Log message appeared:

Logger: frontend.js.latest.202101277
Source: components/system_log/__init__.py:190 
First occurred: 16:56:49 (6 occurrences) 
Last logged: 17:58:55

http://........:8123/hacsfiles/lovelace-tempometer-gauge-card/tempometer-gauge-card.js:334:20 TypeError: undefined is not an object (evaluating 'entity.state')

**Comment by bakboord4** [comment] 2021-02-20 17:25
see above.
reboot is reboot Host of Home Assistant.

**Comment by SNoof85** [comment] 2021-02-24 21:24
could you post the card config ?

**Comment by bakboord4** [comment] 2021-02-25 11:00
1st full example from your readme.

Used card config:
      - type: 'custom:tempometer-gauge-card'
         entity: sensor.bk_luchtdruk
         min: 980
         max: 1050
         entity_min: sensor.barometer_min_this_week
         entity_max: sensor.barometer_max_this_week
         title: Barometer
         decimals: 0
         severity:
           green: 1020
           yellow: 1000
           red: 900

Effect: the view where this card is used in, is completely blanc. (not reported before)

Error.
Log: Logger: frontend.js.latest.202101277
Source: components/system_log/__init__.py:190 
First occurred: 11:40:26 (1 occurrences) 
Last logged: 11:40:26

http://............:8123/hacsfiles/lovelace-tempometer-gauge-card/tempometer-gauge-card.js:334:20 TypeError: undefined is not an object (evaluating 'entity.state')

Without this temp gauge card, all the other cards in this view are presented correctly.

**Comment by bpetrikovics** [comment] 2021-02-26 17:19
Mine is:

type: 'custom:tempometer-gauge-card'
entity: sensor.nrf24_47_pressure
min: 980
max: 1050
title: Barometer
decimals: 1
horizontal: true
severity:
  green: 1020
  yellow: 1000
  red: 900
entity_min: sensor.nrf24_47_pressure_statistics.min_value
entity_max: sensor.nrf24_47_pressure_statistics.max_value

**Comment by SNoof85** [comment] 2021-02-28 20:01
Hey,

I'm sorry about this, i'm not able to reproduce. And i have no idea where this problem is coming from. If your cards renders correct on desktop, i guess this is not an issue from the card's configuration.
I know there's an issue where the card doesn't appears at all if you define entity_min and entity_max to unexisting entities (will fix this) but i don't know for this specific case where the card is partially rendered on companion apps...

**Comment by bpetrikovics** [comment] 2021-02-28 20:52
No worries, I know it's a weird issue. I'm suspecting something with the Android 11 webview as all my other devices have older OS and the companion app works on those properly.

**Comment by bakboord4** [comment] 2021-02-28 21:12
@SNoof85 Thanks for energy put in. For me the card is not working under MacOS as well IOS/iPadOS. But I will try again to find an answer for my problem.

**Comment by SNoof85** [comment] 2021-04-23 07:52
have you been able to get a solution ?

**Comment by bakboord4** [comment] 2021-04-23 09:33
@SNoof85 May found a solution by creating correct _min and_max entities thru using statistics template but I am not sure. 
For me you may close this issue. Thank you for all the energy you put in to it.

**Comment by SNoof85** [comment] 2021-04-23 10:52
Thanks for your feedback

**Closed by SNoof85** 2021-04-23 10:52 UTC
Labels: bug
